wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708975275.144466
    t:
      1:
      - 5
      - 53
      - 55
      - 95
      2:
      - 5
      - 53
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
